### ISSUE TITLE
Reporte Usuario PDF

### ISSUE THREAD

**Issue by AzureGreyes** [ahuamana/prestamistAPP#2]
Se podría agregar el reporte del prestamo por usuario en formato PDF que contenga: 

1. Nombre, dirección, telefono (datos del cliente).

2. Capital, cuotas pagadas, cuotas pendientes y restante.(datos del prestámo).

3. Responsable: el encargado del cobro.

**Comment by ahuamana** [comment]
@AzureGreyes Claro que si!

##Casos de Uso
- El cashier debe permitirle descarg un PDF con el reporte de préstamo con los **datos del cliente** así como **datos del préstamo**
