### ISSUE TITLE
Solicitud es posible agregar mensaje de pago cuando se actualiza el pago

### ISSUE THREAD

**Issue by shakra009** [ahuamana/prestamistAPP#6]
Buenas como va todo espero que todo este bien

por este medio hago la solicitud haber si es posible de agregar la acción de cuando se pague una cuota se envié un mensaje diciendo las cantidad que restan y la información del cliente?

muchas gracias

**Comment by ahuamana** [comment]
Podrias dejar un ejemplo.

**Comment by shakra009** [comment]
val cuotasRestantes = item.quotas ?: 0 - (item.quotasPaid ?: 0)
val mensajePago = "Hola *${nombreCompleto.text}*, has pagado una cuota, faltan ${cuotasRestantes} " +
        "cuotas por pagar de tu préstamo."

// Enviar el mensaje a WhatsApp
openWhatsapp(item.celular, mensajePago)




algo asi

**Comment by ahuamana** [comment]
Podrias detallar un poco mas seguir este formato el uso que se le dara en este formato: recuerda que actualmente existen roles como cashier, admin, superadmin

como: <rol/perfil>
quiero: <accion/actividad>
porque: <beneficio/razon>

Ejemplo:

Como: Cashier
Quiero: Enviar el mensaje al número de WhatsApp a los prestamistas.
Porque: WhatsApp es una de las plataformas de mensajería más utilizadas, por lo que enviar un mensaje por allí asegura que el usuario reciba la notificación de manera rápida y directa. La integración con WhatsApp es fundamental para garantizar la efectividad de la comunicación y que el mensaje llegue al usuario sin demoras.

**Comment by shakra009** [comment]
Cashier 

Me gustaría que cuando el Cashier cobre una o varias cuotas de un préstamo automáticamente dar Cilck en actualizar prestamos 
se envié un mensaje al cliente 

Ejemplo:

Wilson: As pagado la cuota 4 de tu préstamo te restan 5 cuotas a pagar gracias
